import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>


<div className='contents'>

  <Navbar />
      
  <div className='flex flex-row'>

        <Sidebar />
        <div className='flex flex-col'>

        
        {/*  */}

        {children}
        <Footer />
        </div>

  </div>

</div>




        </body>
    </html>
  )
}
